
default: &default
  adapter: postgresql
  encoding: unicode
  username: satoshy
  pool: 5

development:
  <<: *default
  database: test_task_development

test:
  <<: *default
  database: test_task_test

production:
  <<: *default
  database: test_task_production
  username: test_task
  password: <%= ENV['TEST_TASK_DATABASE_PASSWORD'] %>
